application: demozone
version: 1
runtime: python
api_version: 1

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (stweaver/sdk)|
 (stw_batchinfo/sdk)|
 (stw_batchinfo/archive)|
 (stw_docflow/sdk)|
 .hg|
 .DS_Store|
 )$

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /appstats/.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  
- url: /static/(.*)
  static_files: static/\1
  upload: static/.*
  expiration: "180d"

- url: /.*
  script: main.py
